Make pod startup fail if init container fails to clone/install

diff --git a/helm/blueapi/templates/deployment.yaml b/helm/blueapi/templates/deployment.yaml
--- a/helm/blueapi/templates/deployment.yaml
+++ b/helm/blueapi/templates/deployment.yaml
@@ -56,6 +56,7 @@ spec:
           - |
             echo "Setting up scratch area"
             blueapi -c /config/config.yaml setup-scratch
+            if [ $? -ne 0 ]; then echo 'Blueapi failed'; exit 1; fi;
             echo "Exporting venv as artefact"
             cp -r /venv/* /artefacts
         volumeMounts:
